import type { EnemyDef, EnemyTypeId } from '../types.js';

// Orden estable: se usa como índice compacto en los snapshots.
export const ENEMY_ORDER: EnemyTypeId[] = [
  'goblin',
  'runner',
  'brute',
  'bat',
  'armored',
  'shaman',
  'larva',
  'troll',
  'slime',
  'slimelet',
  'ghost',
  'golem',
];

export const ENEMIES: Record<EnemyTypeId, EnemyDef> = {
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    hp: 32,
    speed: 1.5,
    bounty: 4,
    armor: 0,
    radius: 0.26,
    livesCost: 1,
    flying: false,
    color: '#66bb6a',
    cost: 4,
    minWave: 1,
  },
  runner: {
    id: 'runner',
    name: 'Corredor',
    hp: 20,
    speed: 2.6,
    bounty: 4,
    armor: 0,
    radius: 0.22,
    livesCost: 1,
    flying: false,
    color: '#ffca28',
    cost: 5,
    minWave: 2,
  },
  brute: {
    id: 'brute',
    name: 'Bruto',
    hp: 150,
    speed: 0.95,
    bounty: 12,
    armor: 2,
    radius: 0.36,
    livesCost: 2,
    flying: false,
    color: '#8d6e63',
    cost: 13,
    minWave: 5,
  },
  bat: {
    id: 'bat',
    name: 'Murciélago',
    hp: 26,
    speed: 2.0,
    bounty: 5,
    armor: 0,
    radius: 0.24,
    livesCost: 1,
    flying: true,
    color: '#7e57c2',
    cost: 6,
    minWave: 4,
  },
  armored: {
    id: 'armored',
    name: 'Blindado',
    hp: 95,
    speed: 1.2,
    bounty: 10,
    armor: 8,
    radius: 0.3,
    livesCost: 1,
    flying: false,
    color: '#90a4ae',
    cost: 11,
    minWave: 7,
  },
  shaman: {
    id: 'shaman',
    name: 'Chamán',
    hp: 65,
    speed: 1.3,
    bounty: 12,
    armor: 0,
    radius: 0.28,
    livesCost: 1,
    flying: false,
    color: '#26a69a',
    healAura: { radius: 1.7, hps: 14 },
    cost: 12,
    minWave: 9,
  },
  larva: {
    id: 'larva',
    name: 'Larva',
    hp: 9,
    speed: 2.2,
    bounty: 1,
    armor: 0,
    radius: 0.16,
    livesCost: 1,
    flying: false,
    color: '#d4e157',
    cost: 1,
    minWave: 3,
  },
  troll: {
    id: 'troll',
    name: 'Trol',
    hp: 200,
    speed: 1.0,
    bounty: 16,
    armor: 1,
    radius: 0.38,
    livesCost: 2,
    flying: false,
    color: '#5c6bc0',
    regen: 9,
    cost: 17,
    minWave: 12,
  },
  slime: {
    id: 'slime',
    name: 'Baboso',
    hp: 75,
    speed: 1.4,
    bounty: 6,
    armor: 0,
    radius: 0.32,
    livesCost: 1,
    flying: false,
    color: '#29b6f6',
    spawnOnDeath: { type: 'slimelet', count: 2 },
    cost: 10,
    minWave: 8,
  },
  slimelet: {
    id: 'slimelet',
    name: 'Babosín',
    hp: 26,
    speed: 1.8,
    bounty: 2,
    armor: 0,
    radius: 0.2,
    livesCost: 1,
    flying: false,
    color: '#81d4fa',
    cost: 3,
    minWave: 99, // solo aparece al morir un Baboso
  },
  ghost: {
    id: 'ghost',
    name: 'Espectro',
    hp: 58,
    speed: 1.7,
    bounty: 9,
    armor: 0,
    radius: 0.26,
    livesCost: 1,
    flying: false,
    color: '#e0e0e0',
    dodge: 0.3, // esquiva proyectiles; los disparos instantáneos siempre aciertan
    cost: 9,
    minWave: 11,
  },
  golem: {
    id: 'golem',
    name: 'Gólem Ancestral',
    hp: 2600,
    speed: 0.6,
    bounty: 150,
    armor: 6,
    radius: 0.55,
    livesCost: 5,
    flying: false,
    color: '#ef5350',
    boss: true,
    spawnOnDeath: { type: 'brute', count: 3 },
    cost: 0, // los jefes se colocan a mano en el guion de oleadas
    minWave: 99,
  },
};
