import type { MapDef } from '../types.js';

// Los waypoints son [col, fila] de celdas; los enemigos caminan por sus centros.
// Los segmentos entre waypoints deben ser horizontales o verticales.

export const MAPS: MapDef[] = [
  {
    id: 'sendero',
    name: 'El Sendero',
    desc: 'Un camino en S, clásico para empezar.',
    gridW: 20,
    gridH: 12,
    theme: 'grass',
    paths: [
      [
        [0, 2],
        [16, 2],
        [16, 5],
        [3, 5],
        [3, 9],
        [19, 9],
      ],
    ],
    blocked: [
      [8, 0],
      [9, 0],
      [1, 11],
      [18, 0],
      [0, 7],
      [12, 11],
      [19, 4],
    ],
  },
  {
    id: 'tenazas',
    name: 'Las Tenazas',
    desc: 'Dos entradas que convergen: hay que defender ambos flancos.',
    gridW: 20,
    gridH: 12,
    theme: 'desert',
    paths: [
      [
        [0, 1],
        [8, 1],
        [8, 5],
        [13, 5],
        [13, 8],
        [19, 8],
      ],
      [
        [0, 10],
        [6, 10],
        [6, 8],
        [13, 8],
        [19, 8],
      ],
    ],
    blocked: [
      [18, 1],
      [19, 0],
      [0, 5],
      [10, 11],
      [16, 3],
      [3, 4],
    ],
  },
  {
    id: 'espiral',
    name: 'La Espiral',
    desc: 'Camino larguísimo hacia el centro. Ideal para morteros.',
    gridW: 20,
    gridH: 12,
    theme: 'snow',
    paths: [
      [
        [0, 0],
        [19, 0],
        [19, 11],
        [2, 11],
        [2, 3],
        [16, 3],
        [16, 8],
        [6, 8],
        [6, 5],
        [10, 5],
      ],
    ],
    blocked: [
      [0, 11],
      [0, 10],
      [12, 6],
    ],
  },
  {
    id: 'cruce',
    name: 'La Encrucijada',
    desc: 'Mapa grande con dos rutas que se cruzan dos veces. El caos está garantizado.',
    gridW: 24,
    gridH: 14,
    theme: 'grass',
    paths: [
      [
        [0, 4],
        [6, 4],
        [6, 9],
        [12, 9],
        [12, 4],
        [18, 4],
        [18, 9],
        [23, 9],
      ],
      [
        [15, 0],
        [15, 6],
        [9, 6],
        [9, 13],
      ],
    ],
    blocked: [
      [2, 1],
      [21, 2],
      [1, 12],
      [22, 12],
      [19, 0],
      [3, 7],
      [20, 6],
      [10, 11],
      [4, 11],
      [17, 12],
    ],
  },
  {
    id: 'volcan',
    name: 'El Volcán',
    desc: 'Serpentea entre ríos de lava en un mapa grande. Cuidado con el calor.',
    gridW: 26,
    gridH: 15,
    theme: 'volcano',
    paths: [
      [
        [0, 7],
        [4, 7],
        [4, 2],
        [12, 2],
        [12, 12],
        [20, 12],
        [20, 5],
        [25, 5],
      ],
    ],
    blocked: [
      [8, 7],
      [16, 7],
      [2, 13],
      [24, 13],
      [1, 0],
      [24, 0],
      [7, 10],
      [17, 3],
      [23, 9],
      [9, 4],
      [15, 14],
    ],
  },
  {
    id: 'laberinto',
    name: 'El Gran Laberinto',
    desc: 'El camino más largo jamás construido, en el mapa más gigante. Paciencia y morteros.',
    gridW: 28,
    gridH: 16,
    theme: 'desert',
    paths: [
      [
        [0, 1],
        [26, 1],
        [26, 4],
        [2, 4],
        [2, 7],
        [26, 7],
        [26, 10],
        [2, 10],
        [2, 13],
        [27, 13],
      ],
    ],
    blocked: [
      [0, 15],
      [27, 15],
      [0, 3],
      [13, 15],
      [5, 15],
      [22, 15],
      [27, 0],
      [12, 0],
      [0, 12],
      [27, 4],
    ],
  },
  {
    id: 'delta',
    name: 'El Delta',
    desc: 'Tres entradas convergen en una sola salida por la cueva de cristal.',
    gridW: 24,
    gridH: 14,
    theme: 'crystal',
    paths: [
      [
        [0, 2],
        [9, 2],
        [9, 7],
        [23, 7],
      ],
      [
        [0, 12],
        [9, 12],
        [9, 7],
        [23, 7],
      ],
      [
        [16, 0],
        [16, 7],
        [23, 7],
      ],
    ],
    blocked: [
      [3, 7],
      [6, 5],
      [20, 3],
      [20, 11],
      [2, 0],
      [12, 10],
      [13, 4],
      [4, 9],
      [21, 1],
      [12, 12],
    ],
  },
];

export function getMap(id: string): MapDef {
  const m = MAPS.find((m) => m.id === id);
  if (!m) throw new Error(`Mapa desconocido: ${id}`);
  return m;
}
